### ISSUE TITLE
Not actual information need replacement of Plus plan to actual name.

### ISSUE THREAD

**Issue by notras** [ibm-cloud-docs/discovery-data#14]
Plus plan referenced in the documentation not listed and information about  30 days trial as well not listed in the Catalog.

**Comment by michelle-miller** [comment]
the plus plan is being rolled out to different regions in phases. it is currently available in us south only. sorry for the confusion. for more information, see the [release notes](https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-release-notes#23june2021)
