### ISSUE TITLE
Invalid json in Unidirectional code example 

### ISSUE THREAD

**Issue by sherryyyu** [ibm-cloud-docs/discovery-data#15]
The Unidirectional code example on this page is an invalid json:
https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-search-settings

```
"expanded_terms": [
        "car",
        "automobile"
        "vehicle"
      ]
```
The comma after "automobile" is missing. 

Please fix, thanks!

**Comment by michelle-miller** [comment]
Fixed.
<img width="322" alt="Screen Shot 2022-04-06 at 10 56 37 AM" src="https://user-images.githubusercontent.com/17206748/162004456-cdf71dcf-2422-40a3-aa2b-cf7729df6d49.png">

Thank you so much for taking the time to let us know. We appreciate it!
