### ISSUE TITLE
WD Troubleshooting guide disappeared from documentation?

### ISSUE THREAD

**Issue by Peter-den-Haan** [ibm-cloud-docs/discovery-data#16]
Hi,

The CP4D WD Troubleshooting guide seems to have disappeared: 
https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-troubleshoot does not seem to exist any longer.

Can this be made available again?

**Comment by michelle-miller** [comment]
Hi @Peter-den-Haan Thanks for letting us know. The information you are looking for is now located at: https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-troubleshoot-cp4d
(I'm setting up a redirect so the old url will automatically redirect to the new one.)

If you recall, what link did you click which brought you to the 404? Do you remember what page you were on? Thanks again.

**Comment by Peter-den-Haan** [comment]
Michelle,

I think initially I had picked up that doc link from a Support note published on the IBM Support site. Don’t know where.

More recently, I had seen the link referenced multiple times on https://pages.github.ibm.com/Watson-Discovery/wd-scalability-documents/Troubleshooting%20by%20Scaling%20WD/, which has various other explanations and WD scaling/problem solving tips&tricks.
(it would be good if this latter info, and related and linked pages (some of them are not accessible to me), could be made available as a formal repository to the field-teams).

Peter



Peter den Haan
Technical Sales Manager - Data&AI
IBM Technology

Phone: +31-646282521
E-mail: ***@***.******@***.***>
[IBM]
J. Huizingalaan 765
Amsterdam, 1066 VH
Netherlands

Explore IBM products to find the solution that works for your business: https://www.ibm.com/demos


From: Michelle Miller ***@***.***>
Reply to: ibm-cloud-docs/discovery-data ***@***.***>
Date: Wednesday, 6 April 2022 at 16:56
To: ibm-cloud-docs/discovery-data ***@***.***>
Cc: Peter den Haan ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-cloud-docs/discovery-data] WD Troubleshooting guide disappeared from documentation? (Issue #16)

Hi @Peter-den-Haan Thanks for letting us know. The information you are looking for is now located at: https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-troubleshoot-cp4d (I'm setting up a redirect so the old url will automatically ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd


Hi @Peter-den-Haan<https://github.com/Peter-den-Haan> Thanks for letting us know. The information you are looking for is now located at: https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-troubleshoot-cp4d
(I'm setting up a redirect so the old url will automatically redirect to the new one.)

If you recall, what link did you click which brought you to the 404? Do you remember what page you were on? Thanks again.

**Comment by michelle-miller** [comment]
Thanks for providing more detail about where the links were. Given that there are so many places linking to the existing topic, I'm just going to change the file name back to troubleshoot. So, your original links should work again. And scratch what I said before about the new URL. Thanks again for the feedback.

**Comment by michelle-miller** [comment]
The links to the Troubleshooting topic from the scaling document are working again now. Thanks for raising the issue.
