### ISSUE TITLE
Missing whitespace in `Entities (built-in and custom),Keywords, `

### ISSUE THREAD

**Issue by laurachiticariu** [ibm-cloud-docs/discovery-data#17]
In: https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-language-support 

`Entities (built-in and custom),Keywords,` - there is a missing whitespace between `),` and `Keywords` .

It should be corrected in 11 rows in the table.

**Comment by michelle-miller** [comment]
fixed. thanks for letting me know!
