### ISSUE TITLE
HTML markup issue

### ISSUE THREAD

**Issue by laurachiticariu** [ibm-cloud-docs/discovery-data#18]
The bottom of https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-language-support  looks like this:

![image](https://user-images.githubusercontent.com/16584976/189787319-c51266cf-966b-41ec-b5cc-d87279362d43.png)

**Comment by michelle-miller** [comment]
thanks, laura. fixed.

**Comment by laurachiticariu** [comment]
Thanks, Michelle!
