### ISSUE TITLE
Fix for sentiment phrase

### ISSUE THREAD

**Issue by laurachiticariu** [ibm-cloud-docs/discovery-data#19]
In: https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-nlu#nlu-sentiment

` Indicates whether the document has a mix of emotions or not` -> replace with ` Indicates whether the document has a mix of sentiment or not`

`Detecting phrases the express sentiment` -> `Detecting phrases that express sentiment`

**Comment by michelle-miller** [comment]
Hi Laura. Updated. Thanks.
