### ISSUE TITLE
Analyze API is not supported for JAVA SKD?

### ISSUE THREAD

**Issue by fctoibm** [ibm-cloud-docs/discovery-data#6]
It was there, and then it went away in an online document. 
Also, instead of passing a file in Curl,  how can we support sending a text?

**Comment by michelle-miller** [comment]
You can call the analyzeDocument method when you use Discovery in IBM Cloud Pak for Data, not with instances that are hosted in IBM Cloud.
See the documentation: https://cloud.ibm.com/apidocs/discovery-data?code=java#analyzedocument

Looks like the supported file types are:
 [application/json,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/pdf,text/html,application/xhtml+xml]
